MIN:
    train_eval:
        device_id: 0
        src_ntype: drug
        tgt_ntype: disease
        pred_etype: treats
        emb_dim: 68
        hidden_dim: 68
        out_dim: 68
        sample_neg_edges: True
        num_epochs: 200
        num_hops: 5
    
    gnnexp:
        device_id: 0
        src_ntype: drug
        tgt_ntype: disease
        pred_etype: treats
        emb_dim: 68
        hidden_dim: 68
        out_dim: 68
        alpha1: 0.0001
        alpha2: 1.0
    pgexp:
        device_id: 0
        src_ntype: drug
        tgt_ntype: disease
        pred_etype: treats
        emb_dim: 68
        hidden_dim: 68
        out_dim: 68
        alpha1: 0.00001
        alpha2: 0.001
        batch_size: 512
    pagelink:
        device_id: 0
        src_ntype: drug
        tgt_ntype: disease
        pred_etype: treats
        emb_dim: 68
        hidden_dim: 68
        out_dim: 68
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50

aug_citation:
    train_eval:
        device_id: 0
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        sample_neg_edges: True
        num_epochs: 200

    gnnexp:
        device_id: 0
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha1: 0.0001
        alpha2: 2.0
    pgexp:
        device_id: 0
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha1: 0.00001
        alpha2: 0.001
        batch_size: 512
    pagelink:
        device_id: 0
        src_ntype: author
        tgt_ntype: paper
        pred_etype: likes
        emb_dim: 128
        hidden_dim: 128
        out_dim: 128
        alpha: 1.0
        beta: 1.0
        k_core: 3
        num_epochs: 50
        
synthetic:
    train_eval:
        device_id: 0
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        sample_neg_edges: False
        num_epochs: 100
        num_hops: 2
    
    gnnexp:
        device_id: 0
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        alpha1: 0.00001
        alpha2: 0.1
    pgexp:
        device_id: 0
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        alpha1: 0.00001
        alpha2: 1.0
        batch_size: 256
    pagelink:
        device_id: 0
        src_ntype: user
        tgt_ntype: item
        pred_etype: likes
        emb_dim: 64
        hidden_dim: 64
        out_dim: 64
        alpha: 1.0
        beta: 1.0
        k_core: 2
        num_epochs: 20
    
    